using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.EntityFrameworkCore;
using QR_CodeScanner.Properties;
using EntityLayer.Concrete;
using BusinessLayer.Concrete;
using DataAccesLayer.Entity;

namespace QR_CodeScanner.Settings
{
    public partial class FrmUsers : DevExpress.XtraEditors.XtraForm
    {
        IAppUserManager _appUserManager;
        public FrmUsers()
        {
            InitializeComponent();
            _appUserManager = new(new EfAppUserDal());
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            KullaniciListele();
        }

        private void KullaniciListele()
        {
            DataAccesLayer.Concrete.Context dbContext = new DataAccesLayer.Concrete.Context();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Users.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.Users.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());



        }

        private void barButtonItemEkle_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridView1.OptionsView.NewItemRowPosition = DevExpress.XtraGrid.Views.Grid.NewItemRowPosition.Bottom;

        }

        private void barButtonItemDuzenle_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridView1.OptionsBehavior.Editable = true;
        }

        private void barButtonItemSil_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }
    }
}