using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.EntityFrameworkCore;
using EntityLayer.Concrete;
using DataAccesLayer.Concrete;

namespace QR_CodeScanner
{
    public partial class FmEtiketler : DevExpress.XtraEditors.XtraForm
    {
        public FmEtiketler()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DataAccesLayer.Concrete.Context dbContext = new Context();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Files.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.Files.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void gridView1_MouseDown(object sender, MouseEventArgs e)
        {
            var position = MousePosition;
            if (e.Button == MouseButtons.Right)
                popupMenu1.ShowPopup(position);
        }

        private void barButtonItemEkle_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            string reportName = appSettings.ShowInputBox("Rapor Adı", "Rapor Adı", "Modul");
            FrmEtiketReport etiketReport = new FrmEtiketReport();
            Files files = new Files();
            files.FileName = reportName;
            files.ModuleNama = "Etiket";


            
            etiketReport.Show();
        }
    }
}